apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test"
  description: "test"
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/agiertli"
  system: test
  consumesApis: 
    - 